"""
🌸 Flower Recognition Demo — Oxford Flowers 102
Streamlit app để demo nhận diện hoa với ConvNeXt-Tiny & EfficientNet-B3.
Chạy: streamlit run demo_app.py
"""

from __future__ import annotations

import json
from pathlib import Path

import streamlit as st
import torch
from PIL import Image
from torchvision import transforms

from src.flowers102.models import create_model

# ── Paths ────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent
REPORTS = ROOT / "reports"
CHECKPOINTS = ROOT / "checkpoints"

# ── Class-name mapping ──────────────────────────────────────────────────
CAT_TO_NAME: dict[str, str] = json.loads(
    (ROOT / "cat_to_name.json").read_text(encoding="utf-8")
)
# ImageFolder sorts folder names lexicographically: "1","10","100",…
FOLDER_NAMES_SORTED = sorted(CAT_TO_NAME.keys(), key=str)
IDX_TO_NAME = {
    idx: CAT_TO_NAME[folder]
    for idx, folder in enumerate(FOLDER_NAMES_SORTED)
}

# ── Available models ────────────────────────────────────────────────────
# ── Load evaluation summary (generated by evaluate_models.py) ───────────
EVAL_SUMMARY_PATH = REPORTS / "evaluation" / "model_comparison.json"
EVAL_SUMMARY: dict | None = None
if EVAL_SUMMARY_PATH.exists():
    EVAL_SUMMARY = json.loads(EVAL_SUMMARY_PATH.read_text(encoding="utf-8"))

MODEL_CONFIGS = {
    "ConvNeXt-Tiny": {
        "arch": "convnext_tiny",
        "ckpt": CHECKPOINTS / "advanced" / "convnext_tiny_best.pth",
    },
    "EfficientNet-B3": {
        "arch": "efficientnet_b3",
        "ckpt": CHECKPOINTS / "advanced" / "efficientnet_b3_best.pth",
    },
    "Baseline (B0)": {
        "arch": "efficientnet_b0",
        "ckpt": CHECKPOINTS / "baseline_best.pth",
    },
}

# ── Transform (eval) ───────────────────────────────────────────────────
EVAL_TRANSFORM = transforms.Compose(
    [
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ]
)


# ── Model loading (cached) ─────────────────────────────────────────────
@st.cache_resource
def load_model(arch: str, ckpt_path: str) -> torch.nn.Module:
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = create_model(arch, num_classes=102, pretrained=False)
    ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device).eval()
    return model


def predict(model: torch.nn.Module, image: Image.Image, top_k: int = 5):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    x = EVAL_TRANSFORM(image.convert("RGB")).unsqueeze(0).to(device)
    with torch.no_grad():
        logits = model(x)
        probs = torch.softmax(logits, dim=1)[0]
    top = torch.topk(probs, top_k)
    results = []
    for prob, idx in zip(top.values, top.indices):
        results.append((IDX_TO_NAME[idx.item()], float(prob)))
    return results


# ═══════════════════════════════════════════════════════════════════════
#  UI
# ═══════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="🌸 Flower Recognition",
    page_icon="🌸",
    layout="wide",
)

st.title("🌸 Nhận diện hoa — Oxford Flowers 102")
st.markdown(
    "Upload ảnh hoa hoặc chọn từ test set — model sẽ dự đoán loại hoa."
)

# ── Sidebar ─────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("⚙️ Cài đặt")
    model_choice = st.selectbox("Chọn model", list(MODEL_CONFIGS.keys()))
    top_k = st.slider("Số lượng Top-K", min_value=1, max_value=10, value=5)

    st.divider()
    st.header("📊 Kết quả so sánh")
    comparison = REPORTS / "model_comparison.png"
    if comparison.exists():
        st.image(str(comparison), use_container_width=True)

    st.divider()
    st.header("🛠️ Kỹ thuật cải tiến")
    techniques = [
        "2-Stage Fine-tuning (freeze → unfreeze)",
        "RandAugment (num_ops=2, magnitude=9)",
        "Mixup (α=0.2) + CutMix (α=1.0)",
        "Label Smoothing (ε=0.1)",
        "Cosine LR + Linear Warmup (3 epochs)",
        "AMP (Mixed Precision)",
        "Gradient Clipping (max_norm=1.0)",
        "Random Erasing (p=0.1)",
    ]
    for t in techniques:
        st.markdown(f"- {t}")

# ── Load model ──────────────────────────────────────────────────────────
cfg = MODEL_CONFIGS[model_choice]
model = load_model(cfg["arch"], str(cfg["ckpt"]))

# ── Main area ───────────────────────────────────────────────────────────
tab_predict, tab_compare, tab_gallery, tab_about = st.tabs(
    ["🔍 Dự đoán", "⚔️ So sánh Model", "🖼️ Gallery", "ℹ️ Giới thiệu"]
)

# ── Test set images for browsing ─────────────────────────────────────────
TEST_DIR = ROOT / "flower_data" / "flower_data" / "test"

@st.cache_data
def get_test_images() -> dict[str, list[Path]]:
    """Return {flower_name: [image_paths]} from test set."""
    result: dict[str, list[Path]] = {}
    if not TEST_DIR.exists():
        return result
    for folder in sorted(TEST_DIR.iterdir()):
        if folder.is_dir() and folder.name in CAT_TO_NAME:
            name = CAT_TO_NAME[folder.name]
            imgs = sorted(folder.glob("*.jpg")) + sorted(folder.glob("*.png"))
            if imgs:
                result[name] = imgs
    return result

# ── Tab: Predict ────────────────────────────────────────────────────────
with tab_predict:
    col_upload, col_result = st.columns([1, 1], gap="large")

    with col_upload:
        input_mode = st.radio(
            "Nguồn ảnh", ["📂 Chọn từ Test Set", "📤 Upload ảnh"],
            horizontal=True,
        )

        image = None
        selected_label = None

        if input_mode == "📂 Chọn từ Test Set":
            test_images = get_test_images()
            if test_images:
                flower_names = list(test_images.keys())
                chosen_flower = st.selectbox("Chọn loại hoa", flower_names)
                imgs = test_images[chosen_flower]
                # Show thumbnail grid to pick from
                img_cols = st.columns(min(len(imgs), 5))
                chosen_idx = st.number_input(
                    f"Chọn ảnh (1–{len(imgs)})", min_value=1,
                    max_value=len(imgs), value=1, step=1,
                )
                image = Image.open(imgs[chosen_idx - 1])
                selected_label = chosen_flower

                # Preview thumbnails
                for i, c in enumerate(img_cols):
                    idx = (chosen_idx - 1) // 5 * 5 + i
                    if idx < len(imgs):
                        with c:
                            thumb = Image.open(imgs[idx])
                            border = "2px solid #4CAF50" if idx == chosen_idx - 1 else "none"
                            st.image(thumb, caption=f"#{idx+1}", use_container_width=True)
            else:
                st.warning("Không tìm thấy thư mục test set.")
        else:
            uploaded = st.file_uploader(
                "Tải ảnh hoa lên", type=["jpg", "jpeg", "png", "webp"]
            )
            if uploaded is not None:
                image = Image.open(uploaded)

    with col_result:
        if image is not None:
            st.image(image, caption="Ảnh đầu vào", use_container_width=True)

            with st.spinner("Đang dự đoán..."):
                results = predict(model, image, top_k=top_k)

            st.subheader("📋 Kết quả dự đoán")
            top_name, top_conf = results[0]

            # Correct / Incorrect (only when ground truth is known)
            if selected_label is not None:
                if top_name == selected_label:
                    st.success(f"✅ **{top_name}** — Đúng!")
                else:
                    st.error(f"❌ **{top_name}** — Sai! (nhãn đúng: **{selected_label}**)")
            else:
                st.success(f"🌸 **{top_name}**")

            # Confidence score
            st.metric("Confidence", f"{top_conf:.1%}")

            # Low-confidence warning
            if top_conf < 0.5:
                st.warning("⚠️ Confidence thấp — model không chắc chắn về dự đoán này.")
            elif len(results) >= 2 and (top_conf - results[1][1]) < 0.1:
                st.warning(
                    f"⚠️ Top-1 và Top-2 sát nhau "
                    f"({top_name}: {top_conf:.1%} vs {results[1][0]}: {results[1][1]:.1%}) "
                    f"— model đang phân vân."
                )

            # Top-K predictions
            st.markdown("**Top-K dự đoán:**")
            for rank, (name, conf) in enumerate(results, 1):
                col_name, col_bar = st.columns([1, 2])
                with col_name:
                    st.write(f"**#{rank}** {name}")
                with col_bar:
                    st.progress(conf, text=f"{conf:.2%}")

            st.caption(
                "ℹ️ **Confidence** = xác suất softmax của model cho ảnh này. "
                "Không phải accuracy — để xem chất lượng tổng thể, vào tab **So sánh Model**."
            )
        else:
            st.info("👈 Chọn ảnh từ test set hoặc upload ảnh để bắt đầu.")

# ── Tab: Compare ────────────────────────────────────────────────────────
with tab_compare:
    st.subheader("⚔️ So sánh 3 model")

    # ── Dataset-level metrics table ──
    if EVAL_SUMMARY:
        st.markdown("#### 📊 Chất lượng trên toàn bộ Test Set")
        metrics_rows = []
        for key in ["convnext_tiny", "efficientnet_b3", "efficientnet_b0"]:
            if key in EVAL_SUMMARY:
                s = EVAL_SUMMARY[key]
                metrics_rows.append({
                    "Model": s["display_name"],
                    "Top-1 Accuracy": f"{s['accuracy']*100:.2f}%",
                    "Top-5 Accuracy": f"{s['top5_accuracy']*100:.2f}%",
                    "Macro F1": f"{s['macro_f1']:.4f}",
                    "Weighted F1": f"{s['weighted_f1']:.4f}",
                    "ECE ↓": f"{s['ece']:.4f}",
                })
        if metrics_rows:
            st.dataframe(metrics_rows, use_container_width=True, hide_index=True)
        st.caption(
            "**Accuracy/F1** = chất lượng phân loại. "
            "**ECE** = calibration — ECE thấp = confidence đáng tin hơn."
        )
        st.divider()

    # ── Pick image: test set or upload ──
    st.markdown("#### 🖼️ So sánh trên 1 ảnh cụ thể")
    cmp_mode = st.radio(
        "Nguồn ảnh", ["📂 Chọn từ Test Set", "📤 Upload ảnh"],
        horizontal=True, key="cmp_mode",
    )

    cmp_image = None
    cmp_label = None  # ground truth if known

    if cmp_mode == "📂 Chọn từ Test Set":
        test_images = get_test_images()
        if test_images:
            flower_names = list(test_images.keys())
            cmp_flower = st.selectbox("Chọn loại hoa", flower_names, key="cmp_flower")
            cmp_imgs = test_images[cmp_flower]
            cmp_idx = st.number_input(
                f"Chọn ảnh (1–{len(cmp_imgs)})", min_value=1,
                max_value=len(cmp_imgs), value=1, step=1, key="cmp_idx",
            )
            cmp_image = Image.open(cmp_imgs[cmp_idx - 1])
            cmp_label = cmp_flower
    else:
        cmp_uploaded = st.file_uploader(
            "Tải ảnh hoa lên", type=["jpg", "jpeg", "png", "webp"], key="cmp_upload",
        )
        if cmp_uploaded is not None:
            cmp_image = Image.open(cmp_uploaded)

    if cmp_image is not None:
        st.image(cmp_image, caption="Ảnh đầu vào", width=300)
        st.divider()

        cols = st.columns(3)
        compare_models = [
            ("ConvNeXt-Tiny", "convnext_tiny", CHECKPOINTS / "advanced" / "convnext_tiny_best.pth"),
            ("EfficientNet-B3", "efficientnet_b3", CHECKPOINTS / "advanced" / "efficientnet_b3_best.pth"),
            ("Baseline (B0)", "efficientnet_b0", CHECKPOINTS / "baseline_best.pth"),
        ]

        for col, (display_name, key, ckpt_path) in zip(cols, compare_models):
            with col:
                st.markdown(f"### {display_name}")
                m = load_model(key, str(ckpt_path))
                res = predict(m, cmp_image, top_k=3)
                top_name, top_conf = res[0]

                # Correct / Incorrect
                if cmp_label is not None:
                    if top_name == cmp_label:
                        st.success(f"✅ **{top_name}**")
                    else:
                        st.error(f"❌ **{top_name}**")
                else:
                    st.markdown(f"**{top_name}**")

                st.metric("Confidence", f"{top_conf:.1%}")

                for rank, (name, conf) in enumerate(res, 1):
                    st.progress(conf, text=f"#{rank} {name} — {conf:.1%}")

        st.caption(
            "ℹ️ Confidence là score per-image — so sánh chất lượng model "
            "nên dựa vào bảng **Accuracy / F1 / ECE** ở trên."
        )

# ── Tab: Gallery ────────────────────────────────────────────────────────
with tab_gallery:
    st.subheader("Các biểu đồ từ quá trình huấn luyện")
    gallery_images = {
        "Ảnh mẫu các loại hoa": "sample_flowers.png",
        "Data Augmentation demo": "augmentation_demo.png",
        "Training Curves": "training_curves.png",
        "So sánh Model": "model_comparison.png",
        "Phân phối lớp": "class_distribution.png",
        "t-SNE Visualization": "viz_tsne.png",
        "Radar Chart": "viz_radar.png",
        "Heatmap": "viz_heatmap.png",
        "Training 3D": "viz_training_3d.png",
        "BERTScore Bar": "viz_bertscore_bar.png",
    }

    cols = st.columns(3)
    for i, (caption, filename) in enumerate(gallery_images.items()):
        path = REPORTS / filename
        if path.exists():
            with cols[i % 3]:
                st.image(str(path), caption=caption, use_container_width=True)

# ── Tab: About ──────────────────────────────────────────────────────────
with tab_about:
    st.subheader("Giới thiệu dự án")
    st.markdown(
        """
        **Dataset**: Oxford Flowers 102 — 102 loại hoa, 8189 ảnh

        **Pipeline**:
        1. `01_data_audit` — Khảo sát & phân tích dữ liệu
        2. `02_baseline_train` — Huấn luyện baseline (EfficientNet-B0)
        3. `03_advanced_training` — Cải tiến với ConvNeXt-Tiny & EfficientNet-B3
        4. `04_hparam_search` — Tìm siêu tham số tối ưu
        5. `05_evaluation_error_analysis` — Đánh giá & phân tích lỗi
        6. `06_inference_demo` — Demo dự đoán

        **Kết quả**:

        | Model | Top-1 | Top-5 |
        |---|---|---|
        | EfficientNet-B3 | 98.78% | 100.00% |
        | **ConvNeXt-Tiny** | **99.51%** | **100.00%** |
        """
    )
    st.markdown("---")
    st.caption("Nguyễn Quang Bình — 102220095")
